Repository gdgriga/devfestbaltics, pull requests merged in 2018-07, with the labels that each got.

#20 Update tickets sections and make active clickable
  config.toml
  data/tickets.json
  themes/falconf/layouts/index.html
  themes/falconf/layouts/partials/ticket.html
Labels: improvement

#21 Change subtitle width
  themes/falconf/src/styles/textStyles.scss
  themes/falconf/static/css/styles.css
Labels: bug

#26 Add animation to mascot
  themes/falconf/layouts/index.html
  themes/falconf/src/styles/animation.scss
  themes/falconf/static/css/styles.css
  themes/falconf/static/images/phonnie1.svg
  themes/falconf/static/images/phonnie2.svg
  themes/falconf/static/js/app.js
Labels: feature

#27 Change figures section colors
  themes/falconf/src/styles/layout.scss
  themes/falconf/static/css/styles.css
Labels: improvement

#32 Change menu font styles to fit sidebar
  themes/falconf/src/styles/sidebar.scss
Labels: improvement

#33 Add retrospective video to previous event section
  config.toml
  themes/falconf/layouts/index.html
  themes/falconf/src/index.scss
  themes/falconf/src/styles/layout.scss
  themes/falconf/src/styles/section-retrospective.scss
Labels: feature

#34 Use bootstrap classes for responsive video
  themes/falconf/layouts/index.html
Labels: improvement
